apiVersion: v1
data:
  config.yaml: |2+
    metricsPath: "/metrics"
    metricsPort: "8080"
    HttpEndpointConfigs:
      - BaseURL: "httpstat.us"
        Scheme: "https"
        Timeout: 10
        Paths:
          - "200"
          - "503"

kind: ConfigMap
metadata:
  name: metrics-config
