apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  labels:
    app: metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
        - name: metrics-collector
          image: pramod0310/metrics_collector:v1.0
          env:
            - name: ENV_CONFIG_PATH
              value: /vmware/config/config.yaml
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /vmware/config
              name: metrics-config
      volumes:
        - configMap:
            defaultMode: 420
            name: metrics-config
          name: metrics-config
