apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics-collector
  name: metrics-collector
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: metrics-collector
  sessionAffinity: None
  type: ClusterIP
